name: Zig build C++ on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [off, fast, safe, small]

    steps:
    - uses: actions/checkout@v3
    - uses: mlugg/setup-zig@v2
      with:
        version: master

    - name: Build
      run: zig build --release=${{ matrix.build_type }} --summary all

    - name: Test
      run: zig  # TODO: zig build test
